version: '3'
services:
  mysql:
    image: mysql
    container_name: saturn_mysql
    environment:
      MYSQL_ROOT_PASSWORD: saturn
      MYSQL_USER: saturn
      MYSQL_PASSWORD: saturn
      MYSQL_DATABASE: saturn
    ports:
      - "3306:3306"
    command: [ "mysqld", "--default-authentication-plugin=mysql_native_password" ]

  saturn:
    build:
      context: .
    depends_on: 
      - mysql
    container_name: saturn_web_server
    environment:
      SATURN_VAULT_KEY: 219e48d750491d8c1e3728afccfd9ec7
      SATURN_VAULT_IV: 12781563267887344565432124689753
    ports:
      - "8080:8080" 
    volumes: 
      - .:/saturn
    command: ["./wait-for.sh", "mysql:3306", "--", "java", "-jar", "/home/saturn-1.0.4.war"]
